//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea9
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A722D3_vacunadosrdv3Entities : DbContext
    {
        public DB_A722D3_vacunadosrdv3Entities()
            : base("name=DB_A722D3_vacunadosrdv3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<municipios> municipios { get; set; }
        public virtual DbSet<pacientes> pacientes { get; set; }
        public virtual DbSet<provincias> provincias { get; set; }
        public virtual DbSet<TipoSangre> TipoSangre { get; set; }
    }
}
