//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea9
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacientes
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int TipoSangreId { get; set; }
        public int ProvinciaId { get; set; }
        public string Direccion { get; set; }
        public string Le_Dio_Covid { get; set; }
        public string Justificacion { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
    
        public virtual provincias provincias { get; set; }
        public virtual TipoSangre TipoSangre { get; set; }
    }
}
